[project]
name = "cloudmarks"
version = "0.1.0"
description = ""
authors = [
    {name = "MikhailVystrchil",email = "Ratven@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "numpy (>=2.5.2,<3.0.0)",
    "laspy (>=2.7.0,<3.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "pandas (>=3.0.5,<4.0.0)"
]

[tool.poetry.group.dev.dependencies]
    pytest = "^8.3.4"

[tool.pytest.ini_options]
    testpaths = ["tests"]
    python_files = ["test_*.py"]
    addopts = "-ra"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
